import { headerNav } from "./modules/header_nav.js";
import { scrollUp } from "./modules/scroll-up.js";
import { searchBar } from "./modules/searchbar.js";
import { subscriptionsform } from "./modules/subscriptions.js";
import { puzzlegamear } from "./modules/puzzlegamear.js";
headerNav();
scrollUp();
searchBar();
subscriptionsform();
puzzlegamear();
